### ISSUE TITLE
review the reading project

### ISSUE THREAD

**Issue by timm** [txt/mase#1]
the "lets get students to fill in promise" project is specified in https://github.com/txt/mase/blob/master/READING.md

feedback please. still amazed you are willing to do this. the collegiality at this uni.., amazing

 fyi, if you want, i could come into your class to brief your students on this

the project has 2 parts
- part2 is a big essay
- part1 has a seed paper then students work backwards exploring reading one prior paper per week for 8 weeks
- the actual "lets add data to promise" exercise is at the end of that sequence. so we dont ask them to do _real_ work that effects promise until after we've trained them in paper reading
- for your subject, you could
  - not do part2
  - don't walk over 8 papers, but over 4

**Comment by timm** [comment]
Update: a missing bit of the current spec is a **glossary**: the top dozen terms that seem to be key themes in the papers being reviewed. 
- [ ] should add
- [ ] also, for the ASE students (and not emerson's SE students) i would add that that glossary is the seed that grows into the lit reviews

**Comment by timm** [comment]
Also, need to add these notes from Swales (which is a standard text). So the spec should start saying thee things experts know that allow them to read papers faster
- context (prior and subsequent papers)
- parts (tim & emeron's 6 + 5)
- terms (glossary, background knowledge on the words)
- goals (the swale 3)

# Swales’ Three-Move Model for Introductions

## With Revisions and Adaptation for Classroom Use by James Luberda

The following is based upon an empirically-derived model of how “real-world” research article introductions commonly proceed. Note that it is not a set of rules, but rather something of a guide as to what readers of research articles and academic essays are likely to expect (and find), a set of patterns in introductions that facilitate their reading and comprehension. You might think of each “move” below as a kind of verbal action—a “move” a writer will make to have a particular effect on the reader. By constructing an introduction more or less along these lines, you ensure your reader has enough information to follow your essay and make use of the information it contains.

Move 1    Establishing a territory
- In this opening move, the writer may do one or more of the following to broadly sketch out where the  subject of his/her essay falls—the “big picture”
  - Point out the importance of the general subject
  - Make generalizations about the subject
  - Review items of previous research

Move 2    Establishing a niche
- In this move, the writer then indicates to the reader the particular area of the broader subject that the essay will deal with. This can be done using one or more of the following:
  -   Make a counter-claim, i.e. assert something contrary to expectations
  - Indicate a gap in the existing research/thinking
  -  Raise a question about existing research/thinking
  -  Suggest the essay is continuing a tradition, i.e. it is following in the footsteps of previous research/thinking

Move 3    Occupying the niche
- In this move, the writer then sketches out exactly what this particular essay will accomplish in relation to move2, and gives the reader a sense of how the essay will proceed. In general, each of the steps below will appear in this move, in order:
  - Step 1: Outline the purpose of the essay, or state the research that was pursued
  - Step 2: State the principal findings of the essay—what the reader can expect the essay/research will have accomplished for them by the time they get to the end
  - Step 3: Indicate, roughly, the structure of the essay—what will appear in it and in what order

**Comment by CaptainEmerson** [comment]
Some issues/questions with the current document:
- I don't see the PROMISE part at the end
- It looks like it's dual use for both 510 and your course. Can you make a branch just for 510? In it, you can condense it to a 1 or 2 week project, with 4 papers, etc.
- Do you own the copyright to the images?

A suggestion for [how to read papers](http://web.cecs.pdx.edu/~sheard/course/SkolSkillsW06/Lectures.html)

**Comment by timm** [comment]
Managed to make it all one page. 

The se stuff is now the "Fast path" assignment specified at top of page.

And I found some good stuff from PSU

Over to you. Need any more structuring?

t

**Comment by CaptainEmerson** [comment]
Looks good. I think it's doable. Tentatively, I'll have you come in on 8/25 at 8:05AM to talk to my students about it.

**Comment by timm** [comment]
er.... actually, i'm going pass on the 8am visit. happy to leave the experiment to you... which is appropriate since i need to know if you have troubles before i ship to finland and montreal

**Comment by timm** [comment]
mei: 
3471632a52a90a644e0549f6d5f624d82207dc8f

**Comment by timm** [comment]
@CaptainEmerson 
fyi- video on the reading assignment: https://vimeo.com/136412506
