### ISSUE TITLE
got the homeworks done till mid sept

### ISSUE THREAD

**Issue by timm** [txt/mase#2]
any comments ? look at "Homework" and "Code1,Code2,Code3,Code4" at http://tiny.cc/mase

![image](https://cloud.githubusercontent.com/assets/29195/9153606/e5b38852-3e2f-11e5-9588-5f89b796f4dd.png)

**Comment by CaptainEmerson** [comment]
The bottom says "copyright", but also says "no copyright." You can't have both! 

You probably want something like a Creative Commons Attribution license.
